import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '../components/Sidebar'
import AuthProvider from '@/contexts/AuthContext'
import WidgetSection from '@/components/WidgetSection'
import RenderWrapper from './RenderWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <RenderWrapper>
            {children}
          </RenderWrapper>
        </AuthProvider>
      </body>
    </html>
  )
}
